### ISSUE TITLE
CameraScroll doesn't recognise CRS's REPLACEROOM function

### ISSUE THREAD

**Issue by snoodledev** [SchuhBaum/SBCameraScroll#8]
Custom Regions Support adds a conditional link mode called REPLACEROOM, which allows one level to be swapped out for another in certain campaigns. This new room essentially pretends to be the old room, to retain connections and spawns while replacing screens/geometry.

CameraScroll doesn't account for this behaviour, and attempts to load whatever version of the room it last merged - usually the original. As a result, whenever an alternate version of the room is entered, the stitched image of the original room will be displayed without any scrolling, offset from the geometry, and the player will not be able to move beyond the screen they entered from. 

This is visible in some custom regions on the workshop, most notably Stormy Coast and my region The Mast. Attached is an example of the issue in a Mast room - the player is currently in the room TM_B08spear, which is set to replace TM_B08 as Spearmaster. 
![image](https://github.com/SchuhBaum/SBCameraScroll/assets/71858614/ae1807ca-61ec-456a-9233-261feb695063)

**Comment by SchuhBaum** [comment]
Should be fixed in v2.7.2. Let me know if you encounter other situations where this messes things up. (In your example it did not merge the correct files and(!) blacklisted the wrong room.)

**Comment by snoodledev** [comment]
Thanks for the update!
The issue seems to be partially resolved - the replaced rooms seem to load correctly upon entering them. But exiting one of these rooms now seems to often load the incorrect level image - see the linked video, where I exit TM_B08spear and the next 2 rooms have incorrect level images (but correct devtools/geometry), then the third one is correct again (seems like it might load in the image for the room you were in before the current one?)

https://streamable.com/2auant

Confirmed this is on v2.7.2, with only CameraScroll, The Mast, and dependencies/menu-only mods. 
[consoleLog.txt](https://github.com/SchuhBaum/SBCameraScroll/files/13258197/consoleLog.txt)
[LogOutput.log](https://github.com/SchuhBaum/SBCameraScroll/files/13258198/LogOutput.log)

**Comment by SchuhBaum** [comment]
Whoops! My bad. Should be fixed in v2.7.3.

**Comment by snoodledev** [comment]
Seems to all be working now! Thanks :)
